apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  annotations:
    tekton.dev/git-0: github.com 
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: <base64 your privatekey>
  known_hosts: <base64 your repo privatekey known hosts>